In [35]:
%load_ext autoreload
%autoreload 2

In [36]:
import numpy as np
import pandas as pd
from kite_trade import *
import ta
from tqdm import tqdm
import datetime
import pyarrow.parquet as pq
import pyarrow as pa

In [37]:
enctoken = "Y/lOkcIc+rrBLphXcy6yp0lR9S3efh+tLrwZl99CU0Sxf04M1ZMkEjszGbfF+vXkOHzCXvfOUn1UxCA6GeflU2RE8FlUyzKOfpuBLOAbjtYqRzytzax53w=="
kite = KiteApp(enctoken=enctoken)

In [4]:
# nifty_50 = pd.read_csv('data/ind_nifty50list.csv')
# nifty_next_50 = pd.read_csv('data/ind_niftynext50list.csv')
# nifty_mix_500 = pd.read_csv("data/ind_nifty500Multicap502525_list.csv")
# output = "data/append_test.parquet"

# table = pa.Table.from_pandas(nifty_50)
# pq.write_to_dataset(table,root_path = output)
# table = pa.Table.from_pandas(nifty_next_50)
# pq.write_to_dataset(table,root_path = output)
# table = pa.Table.from_pandas(nifty_mix_500)
# pq.write_to_dataset(table,root_path = output)

# df = pd.read_parquet("data/append_test.parquet")

In [7]:
timerframe_list = [
"day",
"minute",
 "3minute",
 "5minute",
 "10minute",
 "15minute",
 "30minute",
 "60minute",]

# instument in nse
inst = pd.DataFrame(kite.instruments("NSE"))
inst_filter = inst.query('(segment == "NSE") & (name != "")')
inst_filter.rename(columns = {"tradingsymbol":'Symbol'},inplace = True)
inst_filter = inst_filter.merge(nifty_mix_500,how = 'inner', on = 'Symbol')

/Users/akash_verma/miniconda3/envs/epat/lib/python3.8/site-packages/pandas/core/frame.py:4300: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [13]:
inst_filter.head(10)

,instrument_token,exchange_token,Symbol,name,last_price,expiry,strike,tick_size,lot_size,instrument_type,segment,exchange,Company Name,Industry,Series,ISIN Code
0,121345,474,3MINDIA,3M INDIA,0.0,None,0.0,0.05,1,EQ,NSE,NSE,3M India Ltd.,Diversified,EQ,INE470A01017
1,1147137,4481,AARTIDRUGS,AARTI DRUGS.,0.0,None,0.0,0.05,1,EQ,NSE,NSE,Aarti Drugs Ltd.,Healthcare,EQ,INE767A01016
2,1378561,5385,AAVAS,AAVAS FINANCIERS,0.0,None,0.0,0.05,1,EQ,NSE,NSE,Aavas Financiers Ltd.,Financial Services,EQ,INE216P01012
3,3329,13,ABB,ABB INDIA,0.0,None,0.0,0.05,1,EQ,NSE,NSE,ABB India Ltd.,Capital Goods,EQ,INE117A01022
4,4583169,17903,ABBOTINDIA,ABBOTT INDIA,0.0,None,0.0,0.05,1,EQ,NSE,NSE,Abbott India Ltd.,Healthcare,EQ,INE358A01014
5,5533185,21614,ABCAPITAL,ADITYA BIRLA CAPITAL.,0.0,None,0.0,0.05,1,EQ,NSE,NSE,Aditya Birla Capital Ltd.,Financial Services,EQ,INE674K01013
6,7707649,30108,ABFRL,ADITYA BIRLA FASHION & RT,0.0,None,0.0,0.05,1,EQ,NSE,NSE,Aditya Birla Fashion and Retail Ltd.,Consumer Services,EQ,INE647O01011
7,1540609,6018,ABSLAMC,ADIT BIRL SUN LIF AMC,0.0,None,0.0,0.05,1,EQ,NSE,NSE,Aditya Birla Sun Life AMC Ltd.,Financial Services,EQ,INE404A01024
8,5633,22,ACC,ACC,0.0,None,0.0,0.05,1,EQ,NSE,NSE,ACC Ltd.,Construction Materials,EQ,INE012A01025
9,6401,25,ADANIENT,ADANI ENTERPRISES,0.0,None,0.0,0.05,1,EQ,NSE,NSE,Adani Enterprises Ltd.,Metals & Mining,EQ,INE423A01024

In [33]:
pd.DataFrame(kite.quote(121345))

                                                                121345
average_price                                                        0
buy_quantity                                                         0
depth                {'buy': [{'price': 0, 'quantity': 0, 'orders':...
instrument_token                                                121345
last_price                                                     23040.5
last_quantity                                                        0
last_trade_time                                    2022-10-28 15:42:43
lower_circuit_limit                                            18432.4
net_change                                                           0
ohlc                 {'open': 22610.3, 'high': 23100, 'low': 22580....
oi                                                                   0
oi_day_high                                                          0
oi_day_low                                                           0
sell_quantity                                                        0
timestamp                                          2022-10-28 18:54:42
upper_circuit_limit                                            27648.5
volume                                                               0

In [12]:
tradingsymbol	Tradingsymbol of the instrument ?
exchange	Name of the exchange (NSE, BSE, NFO, CDS, BCD, MCX)
transaction_type	BUY or SELL
order_type	Order type (MARKET, LIMIT etc.)
quantity	Quantity to transact
product	Margin product to use for the order (margins are blocked based on this) ?
price	The price to execute the order at (for LIMIT orders)
trigger_price	The price at which an order should be triggered (SL, SL-M)
disclosed_quantity	Quantity to disclose publicly (for equity trades)
validity	Order validity (DAY, IOC and TTL)
validity_ttl	Order life span in minutes for TTL validity orders
iceberg_legs	Total number of legs for iceberg order type (number of legs per Iceberg should be between 2 and 10)
iceberg_quantity	Split quantity for each iceberg leg order (quantity/iceberg_legs)
tag	An optional tag to apply to an order to identify it (alphanumeric, max 20 chars)

[]

In [ ]:
def place_order(self, variety, exchange, tradingsymbol, transaction_type, quantity, product, order_type, price=None,
                    validity=None, disclosed_quantity=None, trigger_price=None, squareoff=None, stoploss=None,
                    trailing_stoploss=None, tag=None):

In [42]:
kite.place_order(
    variety='amo' , exchange= "NSE",tradingsymbol ='ACC',transaction_type = 'BUY',quantity = 1,product = 'MIS',order_type= "MARKET" )

{'variety': 'amo', 'exchange': 'NSE', 'tradingsymbol': 'ACC', 'transaction_type': 'BUY', 'quantity': 1, 'product': 'MIS', 'order_type': 'MARKET'}
{'Authorization': 'enctoken Y/lOkcIc+rrBLphXcy6yp0lR9S3efh+tLrwZl99CU0Sxf04M1ZMkEjszGbfF+vXkOHzCXvfOUn1UxCA6GeflU2RE8FlUyzKOfpuBLOAbjtYqRzytzax53w=='}
https://api.kite.trade/orders/amo

In [21]:
kite.ltp()

{}

In [30]:
kite.cancel_order(variety = 'amo', order_id = 221029000008304, parent_order_id=None)

'221029000008304'

In [31]:
kite.margins()

{'equity': {'enabled': True,
  'net': 661.4,
  'available': {'adhoc_margin': 0,
   'cash': 661.4,
   'opening_balance': 661.4,
   'live_balance': 661.4,
   'collateral': 0,
   'intraday_payin': 0},
  'utilised': {'debits': 0,
   'exposure': 0,
   'm2m_realised': 0,
   'm2m_unrealised': 0,
   'option_premium': 0,
   'payout': 0,
   'span': 0,
   'holding_sales': 0,
   'turnover': 0,
   'liquid_collateral': 0,
   'stock_collateral': 0,
   'delivery': 0}},
 'commodity': {'enabled': False,
  'net': 0,
  'available': {'adhoc_margin': 0,
   'cash': 0,
   'opening_balance': 0,
   'live_balance': 0,
   'collateral': 0,
   'intraday_payin': 0},
  'utilised': {'debits': 0,
   'exposure': 0,
   'm2m_realised': 0,
   'm2m_unrealised': 0,
   'option_premium': 0,
   'payout': 0,
   'span': 0,
   'holding_sales': 0,
   'turnover': 0,
   'liquid_collateral': 0,
   'stock_collateral': 0,
   'delivery': 0}}}

In [32]:
kite.orders()

[{'placed_by': 'FC9764',
  'order_id': '221029000008311',
  'exchange_order_id': None,
  'parent_order_id': None,
  'status': 'CANCELLED AMO',
  'status_message': None,
  'status_message_raw': None,
  'order_timestamp': '2022-10-29 19:12:41',
  'exchange_update_timestamp': None,
  'exchange_timestamp': None,
  'variety': 'amo',
  'modified': False,
  'exchange': 'NSE',
  'tradingsymbol': 'ACC',
  'instrument_token': 5633,
  'order_type': 'MARKET',
  'transaction_type': 'BUY',
  'validity': 'DAY',
  'validity_ttl': 0,
  'product': 'MIS',
  'quantity': 1,
  'disclosed_quantity': 0,
  'price': 0,
  'trigger_price': 0,
  'auction_number': None,
  'average_price': 0,
  'filled_quantity': 0,
  'pending_quantity': 1,
  'cancelled_quantity': 0,
  'market_protection': 0,
  'meta': {},
  'tag': None,
  'guid': '01XdC7hi4Lq2g4E'},
 {'placed_by': 'FC9764',
  'order_id': '221029000008304',
  'exchange_order_id': None,
  'parent_order_id': None,
  'status': 'CANCELLED AMO',
  'status_message': None,
  'status_message_raw': None,
  'order_timestamp': '2022-10-29 19:14:50',
  'exchange_update_timestamp': None,
  'exchange_timestamp': None,
  'variety': 'amo',
  'modified': False,
  'exchange': 'NSE',
  'tradingsymbol': 'ACC',
  'instrument_token': 5633,
  'order_type': 'MARKET',
  'transaction_type': 'BUY',
  'validity': 'DAY',
  'validity_ttl': 0,
  'product': 'MIS',
  'quantity': 1,
  'disclosed_quantity': 0,
  'price': 0,
  'trigger_price': 0,
  'auction_number': None,
  'average_price': 0,
  'filled_quantity': 0,
  'pending_quantity': 1,
  'cancelled_quantity': 0,
  'market_protection': 0,
  'meta': {},
  'tag': None,
  'guid': '01Xg431fG7DtVjv'}]